
services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=alkemy_data
    volumes:
      - "./data_api:/var/lib/postgresql/data:rw"
    ports:
      - "5431:5432"
    networks:
      - airflow

networks:
  airflow:
    external:
      name: airflow_default